### ISSUE TITLE
`qvalue` is not available

### ISSUE THREAD

**Issue by miranska** [cbpeterson/TreeBH#1]
Hello,
The following error occurred when I attempted to install the package in R v.4.2.1:
```
> install.packages("TreeBH_1.0.tar.gz", repos = NULL, type = "source")
ERROR: dependency ‘qvalue’ is not available for package ‘TreeBH’
```
Could you please tell me which R library contains the function `qvalue`?  A package called qvalue [exists](https://github.com/StoreyLab/qvalue), but it's not part of CRAN.

**Comment by cbpeterson** [comment]
The qvalue package is now available through Bioconductor at [http://www.bioconductor.org/packages/release/bioc/html/qvalue.html](http://www.bioconductor.org/packages/release/bioc/html/qvalue.html)
